# Generated by Django 5.2.9 on 2026-01-07 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('test_type', models.CharField(choices=[('blood_pressure', 'Blood Pressure'), ('blood_sugar', 'Blood Sugar'), ('cholesterol', 'Cholesterol'), ('hemoglobin', 'Hemoglobin'), ('urinalysis', 'Urinalysis'), ('pregnancy_test', 'Pregnancy Test'), ('malaria_test', 'Malaria Test'), ('hiv_test', 'HIV Test'), ('other', 'Other')], max_length=50)),
                ('test_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_age', models.IntegerField(blank=True, null=True)),
                ('patient_gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('patient_phone', models.CharField(blank=True, max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('reviewed', 'Reviewed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('results', models.TextField(blank=True, help_text='Test results and findings', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or observations', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'role': 'lab_technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests_assigned', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests_requested', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lab_tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(help_text='e.g., Systolic BP, Glucose Level', max_length=255)),
                ('value', models.CharField(help_text='Measured value', max_length=100)),
                ('unit', models.CharField(help_text='e.g., mmHg, mg/dL', max_length=50)),
                ('reference_range', models.CharField(blank=True, help_text='Normal range for this parameter', max_length=100)),
                ('is_normal', models.BooleanField(default=True, help_text='Is value within normal range?')),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements_taken', to=settings.AUTH_USER_MODEL)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='laboratory.labtest')),
            ],
            options={
                'db_table': 'lab_measurements',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['test_number'], name='lab_tests_test_nu_299368_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['status'], name='lab_tests_status_a1f2b5_idx'),
        ),
        migrations.AddIndex(
            model_name='labtest',
            index=models.Index(fields=['patient_name'], name='lab_tests_patient_8cebb0_idx'),
        ),
    ]
