# Generated by Django 5.2.9 on 2026-01-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Cost of the lab test', max_digits=10),
        ),
        migrations.AddField(
            model_name='labtest',
            name='diagnosis',
            field=models.TextField(blank=True, help_text='Medical diagnosis based on test results', null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='paid',
            field=models.BooleanField(default=False, help_text='Payment status'),
        ),
    ]
