# Generated by Django 5.2.9 on 2026-01-07 13:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_labtest_cost_labtest_diagnosis_labtest_paid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(help_text='Unique code for the test type', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Default cost for this test', max_digits=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this test type is available')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_types_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'test_types',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='labtest',
            name='test_type',
            field=models.ForeignKey(help_text='Type of test to perform', on_delete=django.db.models.deletion.PROTECT, related_name='lab_tests', to='laboratory.testtype'),
        ),
    ]
