# Generated by Django 5.2.9 on 2026-01-07 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_testtype_alter_labtest_test_type'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer who is taking the test', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='paid_at',
            field=models.DateTimeField(blank=True, help_text='When payment was made', null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('card', 'Card'), ('mobile', 'Mobile Money'), ('insurance', 'Insurance')], help_text='Method of payment', max_length=20, null=True),
        ),
    ]
