# Generated by Django 5.2.9 on 2026-01-07 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0004_labtest_customer_labtest_paid_at_and_more'),
        ('prescriptions', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='prescription',
            field=models.ForeignKey(blank=True, help_text='Prescription this test is related to (if any)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='prescriptions.prescription'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='sale',
            field=models.ForeignKey(blank=True, help_text='Sale transaction for this test (if paid at POS)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_tests', to='sales.sale'),
        ),
    ]
