# Generated by Django 5.2.9 on 2026-01-07 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacy_name', models.CharField(help_text='Official pharmacy name', max_length=255)),
                ('business_registration_number', models.CharField(blank=True, max_length=100, null=True)),
                ('tax_id', models.CharField(blank=True, help_text='Tax ID/VAT number', max_length=100, null=True)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state_province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('receipt_header', models.TextField(blank=True, help_text='Custom header text for receipts', null=True)),
                ('receipt_footer', models.TextField(blank=True, help_text='Custom footer text for receipts', null=True)),
                ('show_logo_on_receipt', models.BooleanField(default=True)),
                ('business_hours', models.TextField(blank=True, help_text='e.g., Mon-Fri: 9AM-8PM', null=True)),
                ('currency_symbol', models.CharField(default='$', max_length=10)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacy_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pharmacy Settings',
                'verbose_name_plural': 'Pharmacy Settings',
            },
        ),
    ]
