# Generated by Django 5.2.9 on 2026-01-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_pharmacysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('pharmacist', 'Pharmacist'), ('cashier', 'Cashier'), ('lab_technician', 'Lab Technician')], default='cashier', max_length=20),
        ),
    ]
