# Generated by Django 5.2.9 on 2026-01-07 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dosage_form',
            field=models.CharField(blank=True, help_text='e.g., 500mg, 10ml, etc.', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_type',
            field=models.CharField(choices=[('tablet', 'Tablet'), ('capsule', 'Capsule'), ('bottle', 'Bottle'), ('box', 'Box'), ('sachet', 'Sachet'), ('vial', 'Vial'), ('tube', 'Tube'), ('strip', 'Strip'), ('piece', 'Piece'), ('ml', 'Milliliter'), ('mg', 'Milligram'), ('unit', 'Unit')], default='piece', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='units_per_pack',
            field=models.IntegerField(default=1, help_text='Number of units in one pack/box'),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Total quantity in stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, help_text='Price per unit', max_digits=10),
        ),
    ]
